const buildActionType = {
  SHOW_STAP_INFO:"SHOW_STAP_INFO",

  CHANEG_STAGE_OF_1:"CHANEG_STAGE_OF_1",
  CHANEG_STAGE_OF_2:"CHANEG_STAGE_OF_2",
  CHANEG_STAGE_OF_3:"CHANEG_STAGE_OF_3",
  
  CHANGE_STAP_1_QNIQUE_ITEM:"CHANGE_STAP_1_QNIQUE_ITEM",

  CHANEG_STAGE_OF_1_SUCCESS:"CHANEG_STAGE_OF_1_SUCCESS",
  CHANEG_STAGE_OF_2_SUCCESS:"CHANEG_STAGE_OF_2_SUCCESS",
  CHANEG_STAGE_OF_3_SUCCESS:"CHANEG_STAGE_OF_3_SUCCESS",


  
  
  CHANEG_STAGE_OF_1_INFO:"CHANEG_STAGE_OF_1_INFO",
  CHANEG_STAGE_OF_2_INFO:"CHANEG_STAGE_OF_2_INFO",
  CHANEG_STAGE_OF_3_INFO:"CHANEG_STAGE_OF_3_INFO",



  CHANEG_STAGE_OF_1_WARNING:"CHANEG_STAGE_OF_1_WARNING",
  CHANEG_STAGE_OF_2_WARNING:"CHANEG_STAGE_OF_2_WARNING",
  CHANEG_STAGE_OF_3_WARNING:"CHANEG_STAGE_OF_3_WARNING",



  CHANEG_STAGE_OF_1_ERROR:"CHANEG_STAGE_OF_1_ERROR",
  CHANEG_STAGE_OF_2_ERROR:"CHANEG_STAGE_OF_2_ERROR",
  CHANEG_STAGE_OF_3_ERROR:"CHANEG_STAGE_OF_3_ERROR",
  CHANGE_2_TO_HIDE_OPTIONS:"CHANGE_2_TO_HIDE_OPTIONS",
  BUILDING_RUNNING:"BUILDING_RUNNING",
    CHANGE_TOTAL_EP:"CHANGE_TOTAL_EP"

};

export default buildActionType;
