
import { Merienda } from "@/app/components/fonts/font";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import "./globals.css";
import store from "./redux/storage";
const inter = Inter({ subsets: ["latin"] });
import Storage from "./redux/storageInject";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Storage>
      <html lang="en">
        <body
          className={`${inter.className} ${Merienda.className} h-full relative`}
          suppressHydrationWarning={true}
        >
          {children}
        </body>
      </html>
    </Storage>
  );
}


